### ISSUE TITLE
Connection sharing

### ISSUE THREAD

**Issue by sferik** [httprb/http.rb#121]
Now that [v0.6.0 has shipped](https://github.com/tarcieri/http/issues/65), I’ve started benchmarking the [`http` branch of the `twitter` gem](https://github.com/sferik/twitter/tree/http) against [`master`](https://github.com/sferik/twitter), which uses Faraday with Net::HTTP.

While the spec suite runs about 4X faster in the `http` branch, the following real-world example—which outputs the screen names of my Twitter friends that start and end with the letter “a”—performs about 2X slower (5 seconds vs. 10 seconds).

```ruby
require 'twitter'

client = Twitter::REST::Client.new(consumer_key: 'abc', consumer_secret: '123')
client.friend_ids('sferik').each_slice(100) do |slice|
  client.users(slice).select { |u| u.screen_name.match(/^a\w*a$/i) }.each do |user|
    puts user.screen_name
  end
end
```

When I run:

    ruby-prof examples/aa_friends.rb --mode=wall --sort=self --min_percent=1

It produces the following output:

```
 %self      total      self      wait     child     calls  name
 60.58     10.089    10.089     0.000     0.000      189   OpenSSL::SSL::SSLSocket#sysread 
 25.86      4.306     4.306     0.000     0.000        6   OpenSSL::SSL::SSLSocket#connect 
 11.91      1.983     1.983     0.000     0.000        6   TCPSocket#initialize 
```

As you can see, I’m initializing a new TCP socket and calling `connect` for each HTTP request, which takes about a second per request. In the `master` branch, I’m able to share a single HTTP connection across multiple request, which explains why it’s about 5 seconds faster.

How can I share a single connection across multiple HTTP requests with the HTTP gem? Without this feature, I won’t be able to replace `faraday` with `http` in the `twitter` gem. :frowning:

**Comment by sferik** [comment]
Resolved via https://github.com/httprb/http.rb/pull/184..

**Comment by sferik** [comment]
Hmmm…trying to move this issue into the [v0.8.0 milestone](https://github.com/httprb/http.rb/milestones/v0.8.0) but I’m getting an error. Maybe it’s related to the denial of service GitHub was facing earlier today. Anyway, this feature should be released in v0.8.0.

**Comment by sferik** [comment]
@tarcieri @ixti Are you able to change the milestone to v0.8.0?

**Comment by tarcieri** [comment]
@sferik GitHub is giving me an error when I try to do that o_O

**Comment by ixti** [comment]
I found the workaround to assign milestones :D via issues index not from particular issue...

**Comment by sferik** [comment]
@ixti :+1:
