### ISSUE TITLE
HTTP basic auth convert response body to string is hanging

### ISSUE THREAD

**Issue by JuanitoFatas** [httprb/http.rb#152]
Hello!

I am doing a basic auth, when I get the response body back. And convert to string. It hangs.

`HTTP.auth(:basic, authenticate_params).get(FEED_URL)`

returns

```
=> #<HTTP::Response/1.0 200 OK headers=#<HTTP::Headers {"Date"=>"Sun, 17 Aug 2014 04:21:49 GMT", "Server"=>"Apache", "X-Powered-By"=>"PHP/5.3.10-1ubuntu3.12", "Set-Cookie"=>"symfony=4h9fj1r2vvkb2fn0h12bkulgs6; path=/", "Expires"=>"Thu, 19 Nov 1981 08:52:00 GMT", "Cache-Control"=>"no-store, no-cache, must-revalidate, post-check=0, pre-check=0", "Pragma"=>"no-cache", "Vary"=>"Accept-Encoding,User-Agent", "P3p"=>"CP=\"NOI CURa OUR NOR UNI\"", "Connection"=>"close", "Content-Type"=>"application/rss+xml; charset=UTF-8"}>>
```

And `HTTP.auth(:basic, authenticate_params).get(FEED_URL).body`

returns

```
=> #<HTTP::Response::Body:3fc442389c6c @streaming=false>
```

And

`HTTP.auth(:basic, authenticate_params).get(FEED_URL).body.to_s`

Hangs at `to_s`.

Any advices? Thank you!

The relevant code, please see [here](https://github.com/JuanitoFatas/comer_de_tapas/blob/master/lib/comer_de_tapas/client.rb#L140).

**Comment by sferik** [comment]
@JuanitoFatas Any update on this?

**Comment by JuanitoFatas** [comment]
> Any update on this?

Just verify, now works like a charm. Thanks for the reminder.

**Comment by sferik** [comment]
:+1:
