### ISSUE TITLE
Code style changes

### ISSUE THREAD

**Issue by ixti** [httprb/http.rb#172]
- Switch access modifier enforce style to indent (outdent right now)
- Switch from single quotes to double quotes

@sferik if you don't have objections I would like to make the changes from above. I know that it's your personal flavor (outdent access modifiers and single quotes), so would like to get your permission to switch to my personal flavour (indent access modifiers and double quotes). :D

**Comment by sferik** [comment]
No objections from me. I care more about enforcing consistency than any particular coding style. I’m starting to favor double-quotes in my projects as I write more [Crystal](http://crystal-lang.org/).

**Comment by ixti** [comment]
Awesome! Thank you! :heart:

**Comment by tarcieri** [comment]
:thumbsup:
