### ISSUE TITLE
how would I support the following auth, headers, and body?

### ISSUE THREAD

**Issue by angelacode** [httprb/http.rb#174]
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-CreatedBy: admin' \
     -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
     "http://127.0.0.1:8080/1.0/kb/tenants"

**Comment by ixti** [comment]
``` ruby
headers = {
  "Content-Type" => "application/json",
  "X-Killbill-CreatedBy" => "admin"
}

body = '{"apiKey": "bob", "apiSecret": "lazar"}'

HTTP.follow.with(headers).post(url, :body => body)
```

**Comment by angelacode** [comment]
where is the 'u' added?  just in the URL?

**Comment by angelacode** [comment]
answers I go:

``` ruby
headers = {
"Content-Type" => "application/json",
"X-Killbill-CreatedBy" => "admin"
}

body = '{"apiKey": "bob", "apiSecret": "lazar"}'

HTTP.follow.with(headers).post(url, :body => body)
```

**Comment by ixti** [comment]
``` ruby
headers = {
  "Content-Type" => "application/json",
  "X-Killbill-CreatedBy" => "admin"
}

url  = "http://admin:password@127.0.0.1:8080/1.0/kb/tenants"
body = '{"apiKey": "bob", "apiSecret": "lazar"}'

HTTP.follow.with(headers).post(url, :body => body)
```

**Comment by ixti** [comment]
Sorry - first replied from mobile, then saw how it looks - and got to laptop to fix it... :D

**Comment by ixti** [comment]
I'm not sure what `-u` of curl means. If it's Basic auth, then instead of putting it into URL, you can call `#basic_auth` on client:

``` ruby
HTTP.basic_auth(:user => user, :pass => pass)
```

**Comment by angelacode** [comment]
I get an error: HTTP::RequestError: invalid transfer encoding

**Comment by tarcieri** [comment]
@angelacode in the future, would you mind asking these sorts of questions on the Google Group?

https://groups.google.com/forum/#!forum/httprb

We like to keep the issue tracker reserved specifically for bugs.

**Comment by ixti** [comment]
@angelacode Are you passing body as a String? Or is it a Hash? If it's a Hash you need to encode it with JSON:

``` ruby
body = JSON.dump { "apiKey" => "bob", "apiSecret" => "lazar" }
```

**Comment by angelacode** [comment]
Hi, thanks would .to_json be fine, as well?

**Comment by ixti** [comment]
@angelacode Sure. Anything that will return string actually ;))
