### ISSUE TITLE
Robust multipart/related support?

### ISSUE THREAD

**Issue by paradox460** [httprb/http.rb#175]
Apologies if this already exists, but I haven't found any references to it.

----
Sometimes one needs to send data via `multipart/related`. This, so far, has been a huge pain in the ass, with almost every other ruby HTTP solution.

Comparatively, other libraries, such as Node.js' [request](https://github.com/request/request) make it [downright simple](https://github.com/request/request#multipartrelated). If we could get something similar to request's level of `multipart/related` support, it would be awesome. They not only solve the initial issue of crafting multiparts, but they go above and beyond and let you deal with some implementation caveats.

Thanks!

**Comment by ixti** [comment]
That's not exists yet. We only support `multipart/form-data`.

**Comment by ixti** [comment]
In any case this issue related to https://github.com/httprb/form_data.rb rather than HTTP gem itself :D

**Comment by paradox460** [comment]
Awesome, thanks, I'll go see about it there.

Also, really nice to see how this has evolved since you first posted it on reddit. It now can basically replace Typhoeus in my workflows

**Comment by ixti** [comment]
Closing in favor or httprb/form_data.rb#1 :D
