### ISSUE TITLE
Wrong permissions on 0.7.3 gem

### ISSUE THREAD

**Issue by eraserewind** [httprb/http.rb#198]
Hi,

The permissions on the 0.7.3 release are wrong:

```
sandbox:/root@[15:43] # ls -al /usr/local/lib/ruby/gems/2.0/gems/http-0.7.1/lib/
total 22
drwxr-xr-x  3 root  wheel    4 Feb 12 13:25 .
drwxr-xr-x  5 root  wheel   19 Feb 12 13:25 ..
drwxr-xr-x  6 root  wheel   17 Feb 12 13:25 http
-rw-r--r--  1 root  wheel  448 Feb 12 13:25 http.rb
sandbox:/root@[15:43] # ls -al /usr/local/lib/ruby/gems/2.0/gems/http-0.7.3/lib/
total 22
drwxr-xr-x  3 root  wheel    4 Mar 31 15:43 .
drwxr-xr-x  5 root  wheel   19 Mar 31 15:43 ..
drwxr-xr-x  6 root  wheel   17 Mar 31 15:43 http
-rw-r-----  1 root  wheel  448 Mar 31 15:43 http.rb
```

When requiring 'http' as an user, RuyGems raises "LoadError: cannot load such file -- http" because it cannot load the file due to permissions.

Reproduced on Debian Wheezy and FreeBSD 10.0-RELEASE, and Ruby 2.0 & Ruby 2.1

**Comment by ixti** [comment]
Indeed. @tarcieri I'll re-release gem.

**Comment by sferik** [comment]
@ixti Any idea how it got into that state? It appears that this is not just `http.rb` but all files in the gem.

**Comment by sferik** [comment]
@ixti What exactly did you change? I don’t see any permissions changes in the [`0-7-stable` branch](https://github.com/httprb/http.rb/tree/0-7-stable). What can we do to ensure this doesn’t happen again?

**Comment by ixti** [comment]
@eraserewind Thanks for the report, released gem with fixed perms as `0.7.4`.

**Comment by ixti** [comment]
@sferik I have just repacked (re-released) gem. Seems like something on @tarcieri's end. `gem build` on his machine somehow produced gzipped tarball with wrong permissions.

**Comment by tarcieri** [comment]
I'm guessing it probably had to do with the default umask of the laptop I did the release from

**Comment by ixti** [comment]
@tarcieri most likely.

**Comment by eraserewind** [comment]
Thanks guys! :smile_cat:
