### ISSUE TITLE
Persistent connection API

### ISSUE THREAD

**Issue by ixti** [httprb/http.rb#200]
Right now basic usage looks like this:

``` ruby
pclient = HTTP.persistent "https://github.com"
pclient.get("https://github.com/httprb/http.rb").to_s # => http.rb homepage
pclient.get("/httprb/http.rb").to_s # => http.rb homepage, same as above
```

After we have done all our calls we need to close underlying connections:

``` ruby
pclient.close
```

Also, if we try to call another host, e.g.:

``` ruby
pclient.get("https://example.com").to_s
```

It will fail (as expected by our design):

```
HTTP::StateError: Persistence is enabled for https://github.com,
  but we got https://example.com
```

I propose to have different API design, that will provide 2 variants of usage. First one - is pretty simple:

``` ruby
pclient = HTTP.persistent

pclient.get("https://github.com/httprb").to_s
# opens persistent connection to https://github.com
# and retrieves /httprb

pclient.get("https://github.com/explore").to_s
# retrieves /explore

pclient.get("http://example.com").to_s
# closes persistent connection to https://github.com
# opens persistent connection to http://example.com
# retrieves /

pclient.close
# closes persistent connection to http://example.com
```

Second, will provide a better API when you have to deal with a single host only:

``` ruby
HTTP.persistent "https://github.com" do |gh_client|
  gh_client.get("/foo").to_s
  gh_client.get("/bar").to_s
end
# connection is auto-closed
```

**Comment by tarcieri** [comment]
The block form is cool, but I'm not sure I really understand the point of switching origins within the context of a persistent connection?

**Comment by ixti** [comment]
> I'm not sure I really understand the point of switching origins

Now, as you said, I don't know the reason as well. Probably no need, indeed.

**Comment by ixti** [comment]
The questions is now only one. Should `.persistent` with block return persistent client or should it return last expression?

**Comment by tarcieri** [comment]
APIs like `TCPSocket.open` return the last value evaluated. It also seems like the more useful thing to do

**Comment by ixti** [comment]
My personal preference is -- last expressions response:

``` ruby
def pub_keys(users)
  HTTP.persistent("https://github.com") do |http|
    users.map { |u| http.get("/#{u}.keys") }
  end
end
```

**Comment by ixti** [comment]
@tarcieri you beat me to it! :D
