### ISSUE TITLE
Better timeouts API

### ISSUE THREAD

**Issue by ixti** [httprb/http.rb#205]
IMO it worth add a bit more simple way of timeouts configuration:

``` ruby
HTTP.with_timeout(:per_request, :connect => 5, :read => 10, :write => 15) 
```

**Comment by zanker** [comment]
I would keep the ability to set a class, because it let's people write their own still. Although something that's maybe symbol or class would work.

And yea sorry, this slipped my mind. Realized it later when Tony brought it up.

**Comment by tarcieri** [comment]
I think I'd like to prefer the proliferation of `#with_*` prefixed things. I kind of regret introducing that convention in the first place.

I'd suggest `HTTP.timeout`

**Comment by ixti** [comment]
Both points make sense to me, so I guess it can be something like (pseudo code):

``` ruby
module HTTP
  def self.timeout(klass, opts = nil)
    timeout = Timeout[klass].new(opts)
  end

  class Timeout
    def self.[](klass_or_symbol)
      return klass_or_symbol if klass_or_symbol.is_a? Class
      case klass_or_symbol
      when :per_operation then PerOperation
      # ...
      end
    end
  end
end
```
