### ISSUE TITLE
Invalid urlencoding of "=" symbol in request parameters

### ISSUE THREAD

**Issue by cryo28** [httprb/http.rb#211]
httprb 0.8.3

```
HTTP.get('http://localhost:8888/path', params: {param1: "="})
```

```
nc -l 8888
GET /path?param1== HTTP/1.1
Connection: close
Host: localhost:8888
User-Agent: RubyHTTPGem/0.8.3
```

I expected the first line of HTTP request to be ```GET /path?param1=%3D HTTP/1.1```.

One more example:

```
HTTP.get('http://localhost:8888/path', params: {param1: "param2=abc"})
```

```
GET /path?param1=param2=abc HTTP/1.1
Connection: close
Host: localhost:8888
User-Agent: RubyHTTPGem/0.8.3
```

whereas it should have been:

```
GET /path?param1=param2%3Dabc HTTP/1.1
```

**Comment by ixti** [comment]
Thanks for your report. Will fix it shortly.

**Comment by ixti** [comment]
Sorry to mislead you. But after going through description of issue again, I don't find it to be a bug.
Unless I misunderstand something, that's correct behavior and `=` should not be encoded. [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.4) does not says anything about that at all.

Also query string parsers recognize that as expected:

#### Ruby

``` ruby
URI.decode_www_form "foo==&bar=%3D"
# => [["foo", "="], ["bar", "="]]

CGI.parse "foo==&bar=%3D"
# => {"foo"=>["="], "bar"=>["="]}
```

#### Python 3

``` python
from urllib.parse import parse_qs
parse_qs("foo==&bar=%3D")
# => {'foo': ['='], 'bar': ['=']}
```

#### Go

``` go
package main

import "fmt"
import "net/url"

func main() {
  m, _ := url.ParseQuery("foo==&bar=%3D");

  for k, v := range m {
    fmt.Printf("%s: %s\n", k, v);
  }
}

// foo: [=]
// bar: [=]
```

**Comment by ixti** [comment]
If you still think it's a bug and have strong arguments, I'm all ears.
