### ISSUE TITLE
Invalid transfer enconding

### ISSUE THREAD

**Issue by Igorpollo** [httprb/http.rb#213]
Hello,
I'm having the error "Invalid transfer enconding" when trying to send a XML in this code:
````
xml_doc  = Nokogiri::XML(@teste,nil,'UTF-8')
  resposta =  HTTP.headers(:accept => "Content-Type: application/xml;").post('https://desenvolvedor.moip.com.br/sandbox/ws/alpha/EnviarInstrucao/Unica', :body => xml_doc)
```
What this can be?
Thanks

**Comment by ixti** [comment]
First of all you are sending pretty strange headers. Most likely you want to do following:

``` ruby
xml = Nokogiri::XML(@teste, nil, "UTF-8")
url = "https://desenvolvedor.moip.com.br/sandbox/ws/alpha/EnviarInstrucao/Unica"
res = HTTP.headers(:content_type => "application/xml").post(url, :body => xml.to_s)
```

If you want to also instruct remote server that you expect XML response, then:

``` ruby
xml = Nokogiri::XML(@teste, nil, "UTF-8")
url = "https://desenvolvedor.moip.com.br/sandbox/ws/alpha/EnviarInstrucao/Unica"
res = HTTP.headers(:accept => "application/xml", :content_type => "application/xml")
  .post(url, :body => xml.to_s)
```

So, to outline couple of issues with your snippet:

- wrong headers
- `:body` should be a String

**Comment by Igorpollo** [comment]
Thanks...
One more question pls?
How can I do this type off authentication:

'Authorization: Basic BASE64(MOIP_API_TOKEN:MOIP_API_KEY)'
Sorry I'm noob. Thanks

**Comment by ixti** [comment]
If it's a bseic authorization then you can do that like this:

``` ruby
HTTP.basic_auth(:user => MOIP_API_TOKEN, :pass => MOIP_API_KEY)
```

If you need a more "manual" control, then:

``` ruby
HTTP.headers(:authorization => "Bearer #{token}")

# or syntax sugar for that:

HTTP.auth("Bearer #{token}")
```
