### ISSUE TITLE
Wipe timeout support out

### ISSUE THREAD

**Issue by ixti** [httprb/http.rb#214]
@zanker, in face of switching socket related stuff to [socketry](https://github.com/zanker/socketry), I propose to wipe out timeouts support. That will auto-magically resolve #203 and will bring timeouts support and better celluloid integration once we finally switch to socketry. #210 becomes obsolete as well.

**Comment by zanker** [comment]
It definitely should not be removed. For us personally, timeout support is critical, but in general a HTTP client is kind of a lot less useful if you can't control timeouts.

I do want to switch it to Socketry when that's ready, but it's not yet :(

**Comment by ixti** [comment]
Got your point. Agree on timeouts. Just wanted to see celluloid support fixed again :D
