### ISSUE TITLE
Add support for cookies 

### ISSUE THREAD

**Issue by ixti** [httprb/http.rb#220]
We need at least basic-level support for reading/writing cookies, becasue manual setting/parseing `Set-Cookie` headers seems not that fun and "simple"... :D

**Comment by ixti** [comment]
@httprb/owners any suggestions on underlying Set-Cookie parser? Do we want to implement our own lightweight one or use some exisitng (if so - which one)?

**Comment by tarcieri** [comment]
Any reason why we can't just use `CGI::Cookie.parse`?

**Comment by tarcieri** [comment]
Some googling turns up this library, which seems fairly mature, and even fits into our existing naming convention:

https://github.com/sparklemotion/http-cookie

**Comment by ixti** [comment]
That was resolved as of 0.8.9/0.8.10
