### ISSUE TITLE
HTTPS and Celluloid::IO - post_connection_check

### ISSUE THREAD

**Issue by nrbrookes** [httprb/http.rb#228]
```
response = HTTP.via('localhost', 3128).head( "https://www.google.com", ssl_socket_class: Celluloid::IO::SSLSocket )
```

Gives...

```
NoMethodError: undefined method `post_connection_check' for #<Celluloid::IO::SSLSocket:0x00000002d819c0>
```

**Comment by tarcieri** [comment]
You need Celluloid::IO master for this to work

On Thursday, May 14, 2015, nrbrookes <notifications@github.com> wrote:

> response = HTTP.via('localhost', 3128).head( "https://www.google.com", ssl_socket_class: Celluloid::IO::SSLSocket )
>
> Gives...
>
> NoMethodError: undefined method `post_connection_check' for #<Celluloid::IO::SSLSocket:0x00000002d819c0>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/httprb/http.rb/issues/228>.
>


-- 
Tony Arcieri

**Comment by nrbrookes** [comment]
Helpful, thank you.
