### ISSUE TITLE
Testing with mock requests

### ISSUE THREAD

**Issue by JikkuJose** [httprb/http.rb#231]
Is there something like webmock that supports http.rb?

**Comment by zanker** [comment]
Webmock supports http.rb, but you need to be using the latest Webmock.

**Comment by tarcieri** [comment]
@JikkuJose in the future, can you ask questions like this on the mailing list? The issue tracker is for bugs

**Comment by JikkuJose** [comment]
Sure, I will do. I am sorry to have posted in there.
