### ISSUE TITLE
Delegation issues in HTTP::Request::Caching

### ISSUE THREAD

**Issue by headius** [httprb/http.rb#239]
While investigating jruby/jruby#3151, a few issues with the way `Caching` does delegation came to light:

* At least one place, in `conditional_on_changes_to`, an `HTTP::Request` object gets double-delegated. Both the `self.class.new` and `.caching` calls wrap the new `HTTP::Request` object in a delegating `Caching` instance.
* The `Caching` class itself is created before `HTTP::Request` has completed loading, resulting in a `DelegateClass` that does most delegation through `method_missing` rather than through generated, direct delegation methods.

These issues are not strictly bugs, but they likely affect performance. In the case of jruby/jruby#3151, they also exposed an obscure bug in JRuby.

**Comment by tarcieri** [comment]
I'm not really happy with the quality of the caching code. It's caused a lot of sporadic test failures. Having a dependency on rack isn't really something I like either.

Perhaps we could remove it and add it back when/if it's in a better state?

**Comment by zanker** [comment]
I agree with removing the code until something better is done.

**Comment by ixti** [comment]
:+1: for wiping it out.

**Comment by tarcieri** [comment]
Created #240 to revert caching
