### ISSUE TITLE
Caching support (was: Conditional Gets)

### ISSUE THREAD

**Issue by Asmod4n** [httprb/http.rb#77]
Would be nice to have some form of Response caching here, with a simple Hash Store and Memcache API Store, seeing how Github itself doesn't count successfull Conditional Gets towards the API limit.

**Comment by Asmod4n** [comment]
Could someone else take https://github.com/Asmod4n/http/compare/caching over? I am afraid i don't use http.rb anymore and haven't found fixes for some pitfalls for caching (attackers can allocate any amount of ram they want with certain conditions).

**Comment by ixti** [comment]
@Asmod4n I don't think I will be able to jump anytime soon on this issue, but I would like to keep it open if anybody would like to jump on. I have merged your `caching` branch of your repo into `wip/caching-support` on this repo.

**Comment by Asmod4n** [comment]
@ixti thanks a lot, i will try to take a look at it after i have read the new HTTP rfcs regarding caching.

**Comment by ixti** [comment]
Closed by #177 which is in master and was released as 0.8.0.pre

**Comment by sferik** [comment]
@ixti This issue should also be moved into the 0.8.0 milestone. Are you able to do that? I’m still getting an error.

**Comment by ixti** [comment]
@sferik  Same here.
